version: "3.5"

services:

  web:
    container_name: websocket-local-server
    image: bref/fpm-dev-gateway
    ports: 
      - "8000:80"
    volumes:
        - .:/var/task:ro
        - ./storage:/var/task/storage
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public

  php:
    container_name: websocket-php
    image: bref/php-80-fpm-dev
    volumes:
      - .:/var/task

  redis:
    container_name: websocket-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./.docker-compose/redis/.data:/data"