version: "3.5"

services:

  web:
    container_name: websocket-local-server
    image: bref/fpm-dev-gateway
    ports: 
      - "8000:80"
    volumes:
        - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public

  php:
    container_name: websocket-php
    build:
      context: .
      dockerfile: ./.docker-compose/php/Dockerfile
    volumes:
        - .:/var/task

  dynamodb:
    container_name: websocket-dynamodb
    image: amazon/dynamodb-local
    ports: 
      - "8074:8074"
    volumes: 
      - "./.docker-compose/dynamodb/.data:/data"