service: WebSocketServerTest

plugins:
    - ./vendor/bref/bref
    - serverless-dotenv-plugin

provider:
    name: aws
    region: ap-northeast-1
    stage: ${env:APP_ENV}
    runtime: provided.al2
    profile: yuk1
    environment:
        REDIS_HOST:
            "Fn::GetAtt": [CacheCluster, RedisEndpoint.Address]

custom:
    description: "${self:service} Project"
    dotenv:
        include:
            - APP_ENV
            - REDIS_PORT

package:
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**

functions:
    web:
        handler: public/index.php
        timeout: 28
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            - httpApi: '*'
            
    artisan:
        handler: artisan
        timeout: 890
        layers:
            - ${bref:layer.php-80}
            - ${bref:layer.console}

    connectionHandler:
        handler: public/index.php
        layers:
            - ${bref:layer.php-80-fpm}
            - ${bref:layer.php-80}
            - ${bref:layer.console}
        events:
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
    
    defaultHandler:
        handler: public/index.php
        layers:
            - ${bref:layer.php-80-fpm}
            - ${bref:layer.php-80}
            - ${bref:layer.console}
        events:
            - websocket:
                route: $default

    customFooHandler:
        handler: public/index.php
        layers:
            - ${bref:layer.php-80-fpm}
            - ${bref:layer.php-80}
            - ${bref:layer.console}
        events:
            - websocket:
                route: foo

resources:
    - ${file(./.serverless-config/vpc.yml)}
    - ${file(./.serverless-config/private-subnet.yml)}
    - ${file(./.serverless-config/security-group.yml)}
    - ${file(./.serverless-config/cache-cluster.yml)}