Resources:
  SecurityGroup:
    DependsOn: VPC
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "${self:custom.description} SecurityGroup"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "${self:custom.description} SecurityGroup"